version: '3.1'

services:

  mysqld:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
  
  phpmyadmind:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
