version: '3.1'

services:
  mongod:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: devdb
      MONGO_INITDB_ROOT_PASSWORD: password
  mongoexpressd:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: false
      ME_CONFIG_MONGODB_SERVER: mongod
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_USERNAME: devdb
      ME_CONFIG_MONGODB_AUTH_PASSWORD: password
