version: '3.1'

services:

  redisstackd:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      REDIS_ARGS: "--requirepass devpassword --user devuser on >devpassword ~* allcommands --user default off nopass nocommands"
